apiVersion: v1
kind: Service
metadata:
  name: spotifood-service
  namespace: spotifood-namespace
  labels:
    app: spotifood
spec:
  selector:
    app: spotifood
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer